[project]
authors = ["Mridul Seth <git@mriduls.com>"]
channels = ["conda-forge", "scipp"]
description = "Add a short description here"
name = "nexus-to-kafka"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
produce = "python producer.py"
consume = "python consumer.py"

[dependencies]
python = "3.11.*"
jupyterlab = ">=4.2.4"
h5py = ">=3.11.0"
scippneutron = ">=24.8.0"
flatbuffers = ">=24.3.25"
python-flatbuffers = ">=24.3.25"
python-confluent-kafka = ">=2.5.0"
chexus = ">=24.6.0"
numpy = ">=2.1.0"

[pypi-dependencies]
ess-streaming-data-types = ">=0.26.1"
file-writer-control = ">=1.3.0"
